### ISSUE TITLE
merge_ocr_txt.py?

### ISSUE THREAD

**Issue by kba** [OCR-D/workflow-demo#4]
Demo_3 expects a script `merge_ocr_txt.py`. Can you provide that script?

@wrznr

**Comment by wrznr** [comment]
Going to add it to a separate repo tomorrow.

**Comment by kba** [comment]
Thanks, looking forward seeing how you implemented this.

**Comment by wrznr** [comment]
@kba Started this one https://github.com/OCR-D/pyocrd
The structure promises more than it actually does at the moment. However, we will add a few things we put together during the last month to make it worth a module.

**Comment by wrznr** [comment]
Btw. any hints on implementatory details and/or python best practices are more than welcome.
